// "use client"
import AnimateText from '@/components/AnimateText'
import HireMe from '@/components/HireMe'
import { LinkArrow } from '@/components/Icons'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import lightBulb from "../public/images/svgs/miscellaneous_icons_1.svg"
const profilePic = '/images/profile/dp.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0' >
          <div className="flex items-center justify-between w-full">
            <div className='w-1/2'>
              <Image src={profilePic} width={500} height={500} className="w-auto h-auto" alt='Gasal' 
              priority
              sizes='(max-width: 760px) 100vw,
              (max-width: 1200px) 50vw, 33vw'/>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <h1> </h1>
              <AnimateText text='Turning Vision Into Reality With Code And Design.' className='!text-left !text-5xl' />
              <p className='mx-4 text-base font-medium'>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.</p>
                <div className='flex items-center self-start mt-2'>
                  <Link href="/dummy.pdf" target='_blank' className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                  hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-white'>
                    Resume
                    <LinkArrow className='w-6 ml-1' />
                  </Link>
                  <Link href="mailto:gasalgasal246@gmail.com" className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light'>Send a mail</Link>
                </div>
            </div>
          </div>
        </Layout>

        <HireMe />

        <div className='absolute right-8 bottom-8 inline-block w-20'>
        <Image src={lightBulb} alt='Gasal' className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}
